/**
 * The shot list for /how-b, "Parts, stacked": a plain shelf taken apart in
 * the air, two of its parts traded for The Curator's Shelf's, and the whole
 * put back together as you scroll.
 *
 * Direction only, like js/assembly/story.js. Every resting place comes out of
 * js/assembly/curator-shelf.js, which scripts/bake-assembly-story.mjs
 * generates from the builder's own placement engine; nothing here retypes a
 * millimetre. The two parts the bake does not carry are derived from it (see
 * "The plain shelf" below) and scripts/test-assembly-story-b.mjs holds them
 * against the engine's own placement of that shelf.
 *
 * ## The device
 *
 * The page opens on the shelf anyone would picture: a wide base with four
 * wide units stacked square above it. It lifts apart, and then, in the air,
 * the second and third units slide out sideways and the parts of The
 * Curator's Shelf slide in where they were: a slim unit and a post on one
 * tier, a shelf and a post on the next. It comes back together as that
 * shelf, and the page ends on the photograph of it. "Choose different parts
 * and it is a different shelf" is the caption, and it is now what the screen
 * does.
 *
 * ## The plain shelf
 *
 * The bake carries The Curator's Shelf's seven parts and no others. The
 * plain shelf is the same Wide Base, the same Wide Adapter, and three Wide
 * Extensions above it, of which the bake has one (item_007, the top). The
 * other two are further instances of that module, placed by the bake's own
 * numbers: item_007's x, y, rotation and pivot, at the heights the second
 * and third tiers rest at, which the bake states as the joints item_003 and
 * item_005 land on. The engine places a Wide Base, a Wide Adapter and three
 * Wide Extensions exactly there (the test checks), and prices it at
 * Ksh 36,000/- against the Curator's 36,500/-.
 *
 * The adapter stays because it has to: the Slim Extension stands on the two
 * middle tubes only the adapter has, so a swap that left a Wide Extension at
 * tier one would put a post on a board with nothing under it, which is the
 * one thing this system is built never to draw. On screen the adapter is a
 * wide unit with two extra tubes, and the opening caption calls it a unit.
 *
 * ## What the engine does and does not do
 *
 * scroll-story.js interpolates focus boxes and piece offsets between
 * consecutive keys, easing each segment, and carries a piece's last stated
 * offset forward through keys that do not mention it. Two things follow:
 *
 *  - A piece that should move across several keys has to be given its offset
 *    at every one of them, or it stands still until the key that states the
 *    change and then hurries. The lift, the swap and the reassembly are
 *    therefore generated by schedule() below: every key states every moving
 *    piece in its run.
 *  - The ease runs per segment, so a piece's speed is zero at every key it
 *    passes through. "One piece starting while the last is still moving" is
 *    honest to that by giving the overlap segment the last 15% of one
 *    piece's travel and the first 15% of the next's: the one landing slows
 *    into its place as the next one begins, and the momentary stop at the
 *    key is the landing.
 *
 * Nothing is ever hidden. The four arriving parts wait parked off-frame to
 * the left from the first key, so no piece pops into or out of the picture
 * on any aspect ratio up to 21:9; the two leaving parts slide off-frame to
 * the right and stay there.
 *
 * ## Seven beats
 *
 *   0 to 12%    the plain shelf, held, framed on the hero key /how ends on
 *   12 to 40%   it lifts apart, top-down, 120 mm per tier above the base; the
 *               frame opens upward so the shelf is taller than the frame it
 *               started in
 *   40 to 44%   hold, exploded
 *   44 to 66%   the swap, a tier at a time from the bottom: the wide unit
 *               slides out along the shelf's own length to the right, and the
 *               Curator's parts for that tier follow in from the left on the
 *               same track, so nothing crosses anything. Tier two first,
 *               then tier three, overlapping
 *   66 to 74%   hold, exploded: The Curator's Shelf in the air, three pins
 *               naming the parts that came in
 *   74 to 90%   it comes back together bottom-up, base first, a piece
 *               arriving only after what it rests on; the frame closes
 *   90 to 100%  the hero holds, then a small settle outward
 */
(function () {
    "use strict";

    var shelf = window.FrameworkAssemblyShelf;

    /*
     * Every word on the page, in one place, one `id: 'string'` per line so a
     * copy script can rewrite it. The four captions are section 4 of
     * research/landing-strategy.md with only what the new beats required
     * changed: the opening counts the plain shelf's parts, the close names
     * the finish the animation is drawn in. The pin labels are not here: they
     * are the bake's own names for the parts, which are the catalogue's.
     * scripts/test-assembly-story-b.mjs holds all of it and counts em dashes
     * (zero).
     */
    var COPY = {
        parts: {
            title: 'Five parts, one joint.',
            body: 'A base and four units. Each one slides onto a pin on the one below. No tools.'
        },
        apart: {
            title: 'Choose different parts and it is a different shelf.',
            body: 'Taller, wider, a low one for a child\'s room. The price is known before you order.'
        },
        together: {
            title: 'It comes apart again when you move.',
            body: 'Delivered assembled within Nairobi. Start with one unit, from Ksh 6,500/-, and add to it later.'
        },
        hero: {
            title: 'As shown: Ksh 36,500/- in Sage.',
            body: 'The Curator\'s Shelf. Made in our Dagoretti Corner workshop.'
        },
        alt: {
            parts: 'A leg held just above the one below it, showing the pin and the tube it drops into.',
            together: 'The finished shelf seen from an angle.'
        }
    };

    /*
     * The finish.
     *
     * The bake carries Coral, the finish the design was saved in, and /how
     * and /how-a paint with it. This page ends on the photograph of the shelf
     * in Sage, so it paints in Sage: the catalogue's own pair for that finish
     * (assets/shelving/catalog.json, finishes[sage].builder), which
     * scripts/test-assembly-story-b.mjs holds against the catalogue so the
     * two cannot drift apart. The honest permanent form is "finish": "sage"
     * in data/assembly/curator.design.json and a re-bake, which would turn
     * all three pages green at once and is not this file's call.
     */
    var FINISH = { id: 'sage', name: 'Sage', palette: { steel: '#709169', surface: '#C5DCC1' } };

    // ------------------------------------------------------------- helpers

    function baked(id) {
        for (var i = 0; i < shelf.pieces.length; i += 1) {
            if (shelf.pieces[i].id === id) return shelf.pieces[i];
        }
        throw new Error('assembly story: no baked piece "' + id + '"');
    }

    /**
     * A Wide Extension resting at the height the bake says `tierOf` rests
     * at, at the top piece's own x, y, rotation and pivot. Every number is
     * the bake's; only the tier changes.
     */
    function wideExtensionBelow(id, tierOf) {
        var top = baked('item_007');
        var z = baked(tierOf).joints[0][2];
        var height = top.bounds[5] - top.bounds[2];
        return {
            id: id, moduleId: top.moduleId, label: top.label,
            t: [top.t[0], top.t[1], z], rot: top.rot, pivot: top.pivot,
            bounds: [top.bounds[0], top.bounds[1], z, top.bounds[3], top.bounds[4], z + height],
            joints: top.joints.map(function (j) { return [j[0], j[1], z]; }),
            priceKsh: top.priceKsh
        };
    }

    /*
     * The plain shelf's second and third tiers: where the Slim Extension and
     * the Standard Extension rest, a Wide Extension rests instead. `on` is the
     * plain shelf's own support order, which the test checks the engine
     * agrees with.
     */
    var PLAIN = [
        wideExtensionBelow('plain_2', 'item_003'),
        wideExtensionBelow('plain_3', 'item_005')
    ];
    PLAIN[0].on = ['item_002'];
    PLAIN[1].on = ['plain_2'];

    var ALL = shelf.pieces.concat(PLAIN);

    function piece(id) {
        for (var i = 0; i < ALL.length; i += 1) {
            if (ALL[i].id === id) return ALL[i];
        }
        throw new Error('assembly story: no piece "' + id + '"');
    }

    /** The bounding box of some pieces, grown by a margin, as a focus box. */
    function around(ids, pad) {
        var margin = typeof pad === 'number' ? [pad, pad, pad] : pad;
        var box = [Infinity, Infinity, Infinity, -Infinity, -Infinity, -Infinity];
        ids.forEach(function (id) {
            var b = piece(id).bounds;
            for (var axis = 0; axis < 3; axis += 1) {
                if (b[axis] < box[axis]) box[axis] = b[axis];
                if (b[axis + 3] > box[axis + 3]) box[axis + 3] = b[axis + 3];
            }
        });
        return [
            box[0] - margin[0], box[1] - margin[1], box[2] - margin[2],
            box[3] + margin[0], box[4] + margin[1], box[5] + margin[2]
        ];
    }

    /** The same box with its ceiling moved, for opening the frame upward. */
    function upTo(box, z) {
        return [box[0], box[1], box[2], box[3], box[4], z];
    }

    /**
     * A pin's anchor: a piece's front post at mid height, on the left or the
     * right. "Front" is the row of joints nearest the camera, read off the
     * renderer's own view direction, so a camera change moves the anchors by
     * itself; the joints are the bake's.
     */
    function post(id, side) {
        var view = (window.FrameworkDesignerRenderer && window.FrameworkDesignerRenderer.VIEW_DIRECTION)
            || [0.61, -0.61, 0.50];
        var p = piece(id);
        var nearest = -Infinity;
        p.joints.forEach(function (j) { nearest = Math.max(nearest, j[1] * view[1]); });
        var front = p.joints.filter(function (j) { return j[1] * view[1] >= nearest - 1; });
        var pick = front[0];
        front.forEach(function (j) {
            if (side === 'left' ? j[0] < pick[0] : j[0] > pick[0]) pick = j;
        });
        return [pick[0], pick[1], (p.bounds[2] + p.bounds[5]) / 2];
    }

    var everything = shelf.pieces.map(function (p) { return p.id; });

    // ------------------------------------------------------- the explosion

    /*
     * How far each piece rises, from its tier above the base. The base stays
     * on the floor; each tier above it rises 120 mm further than the one
     * below, so the gaps read as gaps and a higher piece never passes through
     * a lower one on the way up or down.
     */
    var LIFT_PER_TIER = 120;
    var TIER = {
        item_001: 0,
        item_002: 1,
        item_003: 2, item_004: 2, plain_2: 2,
        item_005: 3, item_006: 3, plain_3: 3,
        item_007: 4
    };
    function lift(id) { return [0, 0, TIER[id] * LIFT_PER_TIER]; }

    /*
     * Top-down for the lift: the reverse of the order the plain shelf is
     * built in, which is the only order the parts can physically come off.
     * Bottom-up for the reassembly, which is the bake's own support order: a
     * piece arrives only after what it rests on. Within a tier the unit goes
     * before the bare post, as the current story does, so nothing lands in
     * pairs.
     */
    var LIFT_ORDER = ['item_007', 'plain_3', 'plain_2', 'item_002'];
    var LAND_ORDER = ['item_002', 'item_003', 'item_004', 'item_006', 'item_005', 'item_007'];

    // ------------------------------------------------------------ the swap

    /*
     * Sideways is along the shelf's own length, x. In the locked isometric
     * that is the diagonal the boards themselves run along, so a part sliding
     * that way slides the way a drawer does, out of the stack it was in.
     *
     * How far: clear of the frame on any screen. Screen-right is (x + y)
     * over root two, the exploded frame at 21:9 shows about 3,400 mm of it
     * either side of centre, and a wide unit reaches 600 mm from centre, so
     * a part parked four shelf-widths along x (5,680 mm, or 4,016 mm of
     * screen-right) is outside the picture on every aspect ratio up to that.
     * A phone shows about 1,000 mm either side, so there the part is gone
     * well before it stops, and the arriving parts appear a little later
     * than they start; the ease hides both.
     */
    var OUT = 4 * shelf.sizeMm[0];

    /*
     * Each tier is one group: the wide unit leaving and the Curator's parts
     * arriving move together, on the same track, the same distance, so their
     * spacing never changes and nothing can cross. Tier two goes first, then
     * tier three, which is the reassembly's own order kept in the air.
     */
    var SWAP = [
        ['plain_2', 'item_003', 'item_004'],
        ['plain_3', 'item_006', 'item_005']
    ];
    var LEAVING = { plain_2: true, plain_3: true };
    var ARRIVING = ['item_003', 'item_004', 'item_005', 'item_006'];

    function parked(id) { var l = lift(id); return [l[0] - OUT, l[1], l[2]]; }
    function gone(id) { var l = lift(id); return [l[0] + OUT, l[1], l[2]]; }
    function swapFrom(id) { return LEAVING[id] ? lift(id) : parked(id); }
    function swapTo(id) { return LEAVING[id] ? gone(id) : lift(id); }

    /**
     * Keys for a run of pieces moving one after another with a small overlap.
     *
     * Each entry in `order` is a piece or a group of pieces that move
     * together, and has a window of the same length; consecutive windows
     * overlap by `overlap` of the timeline, and in that shared segment the
     * earlier entry does the last `tail` of its travel while the later one
     * does the first `tail` of its own. Every key states every piece in the
     * run, which is what the engine's carry-forward needs to keep them all
     * moving.
     *
     * `at(id)` gives a piece's offset at the start of the run, `to(id)` at the
     * end; the rest is linear between the key times, and the engine eases each
     * segment.
     */
    function schedule(order, start, end, overlap, tail, at, to) {
        var groups = order.map(function (entry) { return [].concat(entry); });
        var n = groups.length;
        var d = (end - start + (n - 1) * overlap) / n;
        var windows = groups.map(function (ids, i) {
            var s = start + i * (d - overlap);
            return { ids: ids, s: round(s), e: round(s + d) };
        });
        var times = [];
        windows.forEach(function (w) {
            if (times.indexOf(w.s) < 0) times.push(w.s);
            if (times.indexOf(w.e) < 0) times.push(w.e);
        });
        times.sort(function (a, b) { return a - b; });

        function fraction(i, t) {
            var w = windows[i];
            if (t <= w.s) return 0;
            if (t >= w.e) return 1;
            var prev = windows[i - 1];
            var next = windows[i + 1];
            var headEnd = prev ? prev.e : w.s;      // overlap with the entry before
            var tailStart = next ? next.s : w.e;    // overlap with the entry after
            var headFrac = prev ? tail : 0;
            var tailFrac = next ? tail : 0;
            if (t <= headEnd) return headFrac * (t - w.s) / Math.max(1e-9, headEnd - w.s);
            if (t >= tailStart) return 1 - tailFrac + tailFrac * (t - tailStart) / Math.max(1e-9, w.e - tailStart);
            return headFrac + (1 - headFrac - tailFrac) * (t - headEnd) / Math.max(1e-9, tailStart - headEnd);
        }

        return times.map(function (t) {
            var pieces = {};
            windows.forEach(function (w, i) {
                var f = fraction(i, t);
                w.ids.forEach(function (id) {
                    var a = at(id);
                    var b = to(id);
                    pieces[id] = { off: [
                        round(a[0] + (b[0] - a[0]) * f),
                        round(a[1] + (b[1] - a[1]) * f),
                        round(a[2] + (b[2] - a[2]) * f)
                    ] };
                });
            });
            return { at: t, pieces: pieces };
        });
    }

    function round(v) { return Math.round(v * 10000) / 10000; }

    var rest = function () { return [0, 0, 0]; };

    // ------------------------------------------------------------- the shot

    // The key /how ends on, used first: the finished shelf with a little room.
    // The plain shelf and The Curator's Shelf have the same outside size, so
    // one frame holds both.
    var HERO = around(everything, [170, 90, 120]);
    // The whole shelf, tighter, for the moment it has just come back together.
    var WHOLE = around(everything, [110, 60, 80]);
    // The frame the exploded shelf needs: the hero box with its ceiling lifted
    // by the top piece's rise. Taller than the frame the story opened in.
    var EXPLODED = upTo(HERO, shelf.boundsMm[5] + TIER.item_007 * LIFT_PER_TIER + 120);

    // The four arriving parts wait off-frame to the left, at the height they
    // will slide in at, from the very first key.
    var waiting = {};
    ARRIVING.forEach(function (id) { waiting[id] = { off: parked(id) }; });

    var cameraKeys = [
        /* --- 1. the plain shelf, held ------------------------------------- */
        { at: 0, focus: HERO, padding: 1.04, pieces: waiting },
        // Opens two percent before the first piece moves, so the reader sees
        // room above the shelf and then the piece rising into it. In the calm
        // tier this is also what puts the cut ahead of the top piece leaving
        // the old frame: calm cuts at the midpoint between camera keys.
        { at: 0.10, focus: HERO, padding: 1.04 },

        /* --- 2. to 5. it lifts apart; hold; the swap; hold ----------------- */
        { at: 0.18, focus: EXPLODED, padding: 1.04 },
        { at: 0.84, focus: EXPLODED, padding: 1.04 },

        /* --- 6. back together: close to the whole ------------------------- */
        // The top piece is the last down and is what holds the ceiling up, so
        // the frame can only close as it descends: 0.84 to 0.96 against its
        // window of about 0.86 to 0.90, and the calm cut at 0.90 lands on a
        // shelf that has just closed.
        { at: 0.96, focus: WHOLE, padding: 1.03 },

        /* --- 7. the hero, with a small settle outward --------------------- */
        { at: 1.0, focus: HERO, padding: 1.04 }
    ];

    var liftKeys = schedule(LIFT_ORDER, 0.12, 0.40, 0.012, 0.15, rest, lift);
    var swapKeys = schedule(SWAP, 0.44, 0.66, 0.06, 0.15, swapFrom, swapTo);
    var landKeys = schedule(LAND_ORDER, 0.74, 0.90, 0.012, 0.15, lift, rest);

    window.FrameworkAssemblyStory = {
        title: shelf.title,
        finish: FINISH.id,
        finishName: FINISH.name,
        palette: FINISH.palette,

        /* Photographs for the tier that should not download geometry: the
           site's own shots of this shelf, the same ones /shelving serves. */
        photoBase: '/images/shelving/configs/',

        /* Resting places, straight from the engine, plus the plain shelf's
           two derived tiers. The animation only ever adds an offset to
           these. */
        pieces: ALL.map(function (p) {
            return { id: p.id, moduleId: p.moduleId, t: p.t, rot: p.rot, pivot: p.pivot };
        }),

        /* For the test: the derived pieces in full, and how far a part
           travels to be out of the picture. */
        plain: PLAIN,
        outMm: OUT,

        keys: cameraKeys.concat(liftKeys, swapKeys, landKeys),

        /*
         * Captions. `from`/`to` are windows on the same timeline; the engine
         * fades each at its edges. The first runs through the lift: it says
         * what the plain shelf is made of, which is what the lift shows. The
         * second opens as the swap begins and runs through the hold: "choose
         * different parts and it is a different shelf" is what the swap does,
         * and it reads on while the drawing is still. The hold adds the pins
         * and no new words.
         */
        captions: [
            { id: 'parts', from: 0.00, to: 0.41, photo: 'asymmetric-display-joint' },
            { id: 'apart', from: 0.42, to: 0.73 },
            { id: 'together', from: 0.74, to: 0.905, photo: 'asymmetric-display-angle' },
            { id: 'hero', from: 0.915, to: 1.08 }
        ].map(function (caption) {
            return {
                id: caption.id, from: caption.from, to: caption.to,
                title: COPY[caption.id].title,
                body: COPY[caption.id].body,
                photo: caption.photo || null,
                photoAlt: COPY.alt[caption.id] || null
            };
        }),

        /*
         * Pins: three, in the hold after the swap, naming the parts that came
         * in by the bake's own names, which are the catalogue's. Each follows
         * its piece, so the dot sits on the part where it is in the air, and
         * each is anchored on a front post at mid height: the slim unit on its
         * left post with the label to the left, the post and the shelf on
         * their right posts with the labels to the right. They run a little
         * into the reassembly and ride down with their parts.
         */
        pins: [
            { id: 'slim', from: 0.665, to: 0.79, follow: 'item_003', point: post('item_003', 'left'), dx: -84, dy: -26 },
            { id: 'booster', from: 0.665, to: 0.79, follow: 'item_004', point: post('item_004', 'right'), dx: 84, dy: -26 },
            { id: 'standard', from: 0.665, to: 0.79, follow: 'item_005', point: post('item_005', 'right'), dx: 84, dy: -26 }
        ].map(function (pin) {
            return {
                id: pin.id, from: pin.from, to: pin.to, follow: pin.follow,
                point: pin.point, dx: pin.dx, dy: pin.dy,
                label: piece(pin.follow).label
            };
        })
    };
})();
