/**
 * The shot list for /how-b, "Parts, stacked": The Curator's Shelf, taken apart
 * in the air and put back together as you scroll.
 *
 * Direction only, like js/assembly/story.js. Every coordinate comes out of
 * js/assembly/curator-shelf.js, which scripts/bake-assembly-story.mjs generates
 * from the builder's own placement engine; nothing here retypes a millimetre.
 *
 * ## The device
 *
 * The current /how and contender A build the shelf up. This one runs the other
 * way: it opens on the finished shelf, lifts it apart into its seven parts,
 * holds that exploded view, and puts it back together bottom-up. The exploded
 * view is the drawing Edwin asked for as Display remarketing creative, so the
 * ad and this page can show the same thing.
 *
 * ## What the engine does and does not do
 *
 * scroll-story.js interpolates focus boxes and piece offsets between
 * consecutive keys, easing each segment, and carries a piece's last stated
 * offset forward through keys that do not mention it. Two things follow, and
 * both shape this file:
 *
 *  - A piece that should move across several keys has to be given its offset
 *    at every one of them, or it stands still until the key that states the
 *    change and then hurries. The lift and the reassembly are therefore
 *    generated by schedule() below rather than written by hand: every key
 *    states every moving piece.
 *  - The ease runs per segment, so a piece's speed is zero at every key it
 *    passes through. "One piece starting while the last is still moving" is
 *    honest to that by giving the overlap segment the last 15% of one piece's
 *    travel and the first 15% of the next's: the one landing slows into its
 *    place as the next one begins to lift, and the momentary stop at the key
 *    is the landing.
 *
 * There is no orbit track. The camera is the builder's locked isometric, and
 * the page is complete in it; see research/landing-b.md for the drift that was
 * considered and not built.
 *
 * ## Five beats
 *
 *   0 to 12%    the whole shelf, held, framed on the hero key /how ends on
 *   12 to 45%   it lifts apart, top-down, 120 mm per tier above the base; the
 *               frame opens upward so the shelf is taller than the frame it
 *               started in
 *   45 to 60%   hold, exploded. Four pins name the part types and nothing else
 *   60 to 86%   it comes back together bottom-up, base first, a piece arriving
 *               only after what it rests on; the frame closes to the whole
 *   86 to 100%  the hero holds, then a small settle outward
 */
(function () {
    "use strict";

    var shelf = window.FrameworkAssemblyShelf;

    /*
     * Every word on the page, in one place, one `id: 'string'` per line so a
     * copy script can rewrite it. The strings are section 4 of
     * research/landing-strategy.md, verbatim; scripts/test-assembly-story-b.mjs
     * checks them against the brief and counts em dashes (zero).
     */
    var COPY = {
        parts: {
            title: 'Seven parts, one joint.',
            body: 'A base, three units, two posts and a shelf. Each one slides onto a pin on the one below. No tools.'
        },
        apart: {
            title: 'Choose different parts and it is a different shelf.',
            body: 'Taller, wider, a low one for a child\'s room. The price is known before you order.'
        },
        together: {
            title: 'It comes apart again when you move.',
            body: 'Delivered assembled within Nairobi. Start with one unit, from Ksh 6,500/-, and add to it later.'
        },
        hero: {
            title: 'As shown: Ksh 36,500/- in Coral.',
            body: 'The Curator\'s Shelf. Made in our Dagoretti Corner workshop.'
        },
        pins: {
            base: 'base',
            unit: 'unit',
            post: 'post',
            shelf: 'shelf'
        },
        alt: {
            parts: 'A leg held just above the one below it, showing the pin and the tube it drops into.',
            together: 'The finished shelf seen from an angle.',
            hero: 'The finished shelf holding books, bowls and small figures.'
        }
    };

    // ------------------------------------------------------------- helpers

    function piece(id) {
        for (var i = 0; i < shelf.pieces.length; i += 1) {
            if (shelf.pieces[i].id === id) return shelf.pieces[i];
        }
        throw new Error('assembly story: no piece "' + id + '"');
    }

    /** The bounding box of some pieces, grown by a margin, as a focus box. */
    function around(ids, pad) {
        var margin = typeof pad === 'number' ? [pad, pad, pad] : pad;
        var box = [Infinity, Infinity, Infinity, -Infinity, -Infinity, -Infinity];
        ids.forEach(function (id) {
            var b = piece(id).bounds;
            for (var axis = 0; axis < 3; axis += 1) {
                if (b[axis] < box[axis]) box[axis] = b[axis];
                if (b[axis + 3] > box[axis + 3]) box[axis + 3] = b[axis + 3];
            }
        });
        return [
            box[0] - margin[0], box[1] - margin[1], box[2] - margin[2],
            box[3] + margin[0], box[4] + margin[1], box[5] + margin[2]
        ];
    }

    /** The same box with its ceiling moved, for opening the frame upward. */
    function upTo(box, z) {
        return [box[0], box[1], box[2], box[3], box[4], z];
    }

    var everything = shelf.pieces.map(function (p) { return p.id; });

    // ------------------------------------------------------- the explosion

    /*
     * How far each piece rises, from its tier above the base. The base stays
     * on the floor; each tier above it rises 120 mm further than the one
     * below, so the gaps read as gaps and a higher piece never passes through
     * a lower one on the way up or down.
     */
    var LIFT_PER_TIER = 120;
    var TIER = {
        item_001: 0,
        item_002: 1,
        item_003: 2, item_004: 2,
        item_005: 3, item_006: 3,
        item_007: 4
    };
    function lift(id) { return [0, 0, TIER[id] * LIFT_PER_TIER]; }

    /*
     * Top-down for the lift: the reverse of the order the shelf is built in,
     * which is the only order the parts can physically come off. Bottom-up for
     * the reassembly, which is the bake's own support order: a piece arrives
     * only after what it rests on. Within a tier the unit goes before the bare
     * post, as the current story does, so nothing lands in pairs.
     */
    var LIFT_ORDER = ['item_007', 'item_005', 'item_006', 'item_004', 'item_003', 'item_002'];
    var LAND_ORDER = ['item_002', 'item_003', 'item_004', 'item_006', 'item_005', 'item_007'];

    /**
     * Keys for a run of pieces moving one after another with a small overlap.
     *
     * Each piece has a window of the same length; consecutive windows overlap
     * by `overlap` of the timeline, and in that shared segment the earlier
     * piece does the last `tail` of its travel while the later one does the
     * first `tail` of its own. Every key states every piece in the run, which
     * is what the engine's carry-forward needs to keep them all moving.
     *
     * `at(id)` gives a piece's offset at the start of the run, `to(id)` at the
     * end; the rest is linear between the key times, and the engine eases each
     * segment.
     */
    function schedule(order, start, end, overlap, tail, at, to) {
        var n = order.length;
        var d = (end - start + (n - 1) * overlap) / n;
        var windows = order.map(function (id, i) {
            var s = start + i * (d - overlap);
            return { id: id, s: round(s), e: round(s + d) };
        });
        var times = [];
        windows.forEach(function (w) {
            if (times.indexOf(w.s) < 0) times.push(w.s);
            if (times.indexOf(w.e) < 0) times.push(w.e);
        });
        times.sort(function (a, b) { return a - b; });

        function fraction(i, t) {
            var w = windows[i];
            if (t <= w.s) return 0;
            if (t >= w.e) return 1;
            var prev = windows[i - 1];
            var next = windows[i + 1];
            var headEnd = prev ? prev.e : w.s;      // overlap with the piece before
            var tailStart = next ? next.s : w.e;    // overlap with the piece after
            var headFrac = prev ? tail : 0;
            var tailFrac = next ? tail : 0;
            if (t <= headEnd) return headFrac * (t - w.s) / Math.max(1e-9, headEnd - w.s);
            if (t >= tailStart) return 1 - tailFrac + tailFrac * (t - tailStart) / Math.max(1e-9, w.e - tailStart);
            return headFrac + (1 - headFrac - tailFrac) * (t - headEnd) / Math.max(1e-9, tailStart - headEnd);
        }

        return times.map(function (t) {
            var pieces = {};
            windows.forEach(function (w, i) {
                var f = fraction(i, t);
                var a = at(w.id);
                var b = to(w.id);
                pieces[w.id] = { off: [
                    round(a[0] + (b[0] - a[0]) * f),
                    round(a[1] + (b[1] - a[1]) * f),
                    round(a[2] + (b[2] - a[2]) * f)
                ] };
            });
            return { at: t, pieces: pieces };
        });
    }

    function round(v) { return Math.round(v * 10000) / 10000; }

    var rest = function () { return [0, 0, 0]; };

    // ------------------------------------------------------------- the shot

    // The key /how ends on, used first: the finished shelf with a little room.
    var HERO = around(everything, [170, 90, 120]);
    // The whole shelf, tighter, for the moment it has just come back together.
    var WHOLE = around(everything, [110, 60, 80]);
    // The frame the exploded shelf needs: the hero box with its ceiling lifted
    // by the top piece's rise. Taller than the frame the story opened in.
    var EXPLODED = upTo(HERO, shelf.boundsMm[5] + TIER.item_007 * LIFT_PER_TIER + 120);

    var cameraKeys = [
        /* --- 1. the whole shelf, held ------------------------------------- */
        { at: 0, focus: HERO, padding: 1.04 },
        // Opens two percent before the first piece moves, so the reader sees
        // room above the shelf and then the piece rising into it. In the calm
        // tier this is also what puts the cut ahead of the top piece leaving
        // the old frame: calm cuts at the midpoint between camera keys.
        { at: 0.10, focus: HERO, padding: 1.04 },

        /* --- 2. and 3. it lifts apart; hold ------------------------------- */
        { at: 0.18, focus: EXPLODED, padding: 1.04 },
        { at: 0.80, focus: EXPLODED, padding: 1.04 },

        /* --- 4. back together: close to the whole ------------------------- */
        // The top piece is the last down and is what holds the ceiling up, so
        // the frame can only close as it descends: 0.80 to 0.92 against its
        // window of about 0.81 to 0.86, and the calm cut at 0.86 lands on a
        // shelf that has just closed.
        { at: 0.92, focus: WHOLE, padding: 1.03 },

        /* --- 5. the hero, with a small settle outward --------------------- */
        { at: 1.0, focus: HERO, padding: 1.04 }
    ];

    var liftKeys = schedule(LIFT_ORDER, 0.12, 0.45, 0.012, 0.15, rest, lift);
    var landKeys = schedule(LAND_ORDER, 0.60, 0.86, 0.012, 0.15, lift, rest);

    window.FrameworkAssemblyStory = {
        title: shelf.title,
        finish: shelf.finish,
        palette: shelf.palette,

        /* Photographs for the tier that should not download geometry: the
           site's own shots of this shelf, the same ones /shelving serves. */
        photoBase: '/images/shelving/configs/',

        /* Resting places, straight from the engine. The animation only ever
           adds an offset to these. */
        pieces: shelf.pieces.map(function (p) {
            return { id: p.id, moduleId: p.moduleId, t: p.t, rot: p.rot, pivot: p.pivot };
        }),

        keys: cameraKeys.concat(liftKeys, landKeys),

        /*
         * Captions. `from`/`to` are windows on the same timeline; the engine
         * fades each at its edges. The second one runs through the hold on
         * purpose: "choose different parts and it is a different shelf" is
         * what the exploded drawing says, and it reads best while the drawing
         * is still. The hold adds the pins and no new words.
         */
        captions: [
            { id: 'parts', from: 0.00, to: 0.115, photo: 'asymmetric-display-joint' },
            { id: 'apart', from: 0.125, to: 0.595 },
            { id: 'together', from: 0.605, to: 0.895, photo: 'asymmetric-display-angle' },
            { id: 'hero', from: 0.905, to: 1.08, photo: 'asymmetric-display-populated' }
        ].map(function (caption) {
            return {
                id: caption.id, from: caption.from, to: caption.to,
                title: COPY[caption.id].title,
                body: COPY[caption.id].body,
                photo: caption.photo || null,
                photoAlt: COPY.alt[caption.id] || null
            };
        }),

        /*
         * Pins: four, in the hold only, naming the part types on the drawing.
         * Each follows its piece, so the dot sits on the part where it is in
         * the air rather than where it will land. `point` is the anchor with
         * the shelf assembled: a post mid-height for the base, the unit and
         * the bare post, and the front edge of the long board for the shelf.
         */
        pins: [
            { id: 'base', from: 0.45, to: 0.60, follow: 'item_001', point: [1143, 0, 230], dx: 84, dy: -26 },
            { id: 'unit', from: 0.45, to: 0.60, follow: 'item_003', point: [0, 0, 875], dx: -84, dy: -26 },
            { id: 'post', from: 0.45, to: 0.60, follow: 'item_004', point: [1143, 0, 875], dx: 84, dy: -26 },
            { id: 'shelf', from: 0.45, to: 0.60, follow: 'item_005', point: [792, -10, 1290], dx: 96, dy: -34 }
        ].map(function (pin) {
            return {
                id: pin.id, from: pin.from, to: pin.to, follow: pin.follow || null,
                point: pin.point, dx: pin.dx, dy: pin.dy,
                label: COPY.pins[pin.id]
            };
        })
    };
})();
